/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Item {
    id: bigint;
    hashtag: string;
    ownerPrincipal: string;
    name: string;
    description: string;
    pricePerDay?: bigint;
    borrowerPrincipal?: string;
    category: string;
    pricePerMonth?: bigint;
    location: string;
}
export interface BorrowRequest {
    status: RequestStatus;
    itemId: bigint;
    borrowTime: bigint;
    borrowerPrincipal: string;
}
export interface FoundItem {
    id: bigint;
    status: LostFoundStatus;
    finderPrincipal: string;
    contactInfo: string;
    description: string;
    receiver?: string;
    pickUpLocation: string;
}
export interface Profile {
    contactInfo: string;
    name: string;
}
export interface LostItem {
    id: bigint;
    status: LostFoundStatus;
    contactInfo: string;
    description: string;
    reporterPrincipal: string;
    lastSeenLocation: string;
}
export enum LostFoundStatus {
    resolved = "resolved",
    active = "active"
}
export enum RequestStatus {
    pending = "pending",
    denied = "denied",
    approved = "approved"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFoundItem(description: string, pickUpLocation: string, contactInfo: string): Promise<bigint>;
    addItem(category: string, hashtag: string, name: string, description: string, pricePerDay: bigint | null, pricePerMonth: bigint | null, location: string): Promise<bigint>;
    addLostItem(description: string, lastSeenLocation: string, contactInfo: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBorrowRequest(itemId: bigint, borrowTime: bigint): Promise<void>;
    filterItemsByCategory(category: string): Promise<Array<Item>>;
    filterItemsByHashtag(hashtag: string): Promise<Array<Item>>;
    getAllItems(): Promise<Array<Item>>;
    getAvailableItems(): Promise<Array<Item>>;
    /**
     * / Get the caller's own profile. Requires #user role.
     */
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFoundItems(): Promise<Array<FoundItem>>;
    /**
     * / Get items currently borrowed by a specific user.
     * / Caller must be that user or an admin to protect borrowing privacy.
     */
    getItemsByBorrower(borrowerPrincipal: string): Promise<Array<Item>>;
    getItemsByOwner(ownerPrincipal: string): Promise<Array<Item>>;
    getLostItems(): Promise<Array<LostItem>>;
    /**
     * / Get borrow history for a given principal text. Caller must own that identity or be admin.
     */
    getUserBorrowingHistory(userPrincipal: string): Promise<Array<BorrowRequest>>;
    /**
     * / Get any user's profile. Caller must be the same user or an admin.
     */
    getUserProfile(user: Principal): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    resolveFoundItem(id: bigint, receiver: string): Promise<void>;
    resolveLostItem(id: bigint): Promise<void>;
    /**
     * / Save the caller's own profile. Requires #user role.
     */
    saveCallerUserProfile(profile: Profile): Promise<void>;
    searchItemsByName(searchTerm: string): Promise<Array<Item>>;
    updateBorrowRequestStatus(itemId: bigint, newStatus: RequestStatus): Promise<void>;
}
import type { BorrowRequest as _BorrowRequest, FoundItem as _FoundItem, Item as _Item, LostFoundStatus as _LostFoundStatus, LostItem as _LostItem, Profile as _Profile, RequestStatus as _RequestStatus, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFoundItem(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFoundItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFoundItem(arg0, arg1, arg2);
            return result;
        }
    }
    async addItem(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint | null, arg5: bigint | null, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async addLostItem(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLostItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLostItem(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBorrowRequest(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBorrowRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBorrowRequest(arg0, arg1);
            return result;
        }
    }
    async filterItemsByCategory(arg0: string): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterItemsByCategory(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterItemsByCategory(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterItemsByHashtag(arg0: string): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterItemsByHashtag(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterItemsByHashtag(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllItems();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllItems();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableItems();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableItems();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoundItems(): Promise<Array<FoundItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoundItems();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoundItems();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemsByBorrower(arg0: string): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsByBorrower(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsByBorrower(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemsByOwner(arg0: string): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsByOwner(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsByOwner(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLostItems(): Promise<Array<LostItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLostItems();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLostItems();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBorrowingHistory(arg0: string): Promise<Array<BorrowRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBorrowingHistory(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBorrowingHistory(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resolveFoundItem(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveFoundItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveFoundItem(arg0, arg1);
            return result;
        }
    }
    async resolveLostItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveLostItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveLostItem(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchItemsByName(arg0: string): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchItemsByName(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchItemsByName(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBorrowRequestStatus(arg0: bigint, arg1: RequestStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBorrowRequestStatus(arg0, to_candid_RequestStatus_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBorrowRequestStatus(arg0, to_candid_RequestStatus_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BorrowRequest_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BorrowRequest): BorrowRequest {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_FoundItem_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoundItem): FoundItem {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Item_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_LostFoundStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LostFoundStatus): LostFoundStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_LostItem_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LostItem): LostItem {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LostFoundStatus;
    finderPrincipal: string;
    contactInfo: string;
    description: string;
    receiver: [] | [string];
    pickUpLocation: string;
}): {
    id: bigint;
    status: LostFoundStatus;
    finderPrincipal: string;
    contactInfo: string;
    description: string;
    receiver?: string;
    pickUpLocation: string;
} {
    return {
        id: value.id,
        status: from_candid_LostFoundStatus_n15(_uploadFile, _downloadFile, value.status),
        finderPrincipal: value.finderPrincipal,
        contactInfo: value.contactInfo,
        description: value.description,
        receiver: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.receiver)),
        pickUpLocation: value.pickUpLocation
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LostFoundStatus;
    contactInfo: string;
    description: string;
    reporterPrincipal: string;
    lastSeenLocation: string;
}): {
    id: bigint;
    status: LostFoundStatus;
    contactInfo: string;
    description: string;
    reporterPrincipal: string;
    lastSeenLocation: string;
} {
    return {
        id: value.id,
        status: from_candid_LostFoundStatus_n15(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        description: value.description,
        reporterPrincipal: value.reporterPrincipal,
        lastSeenLocation: value.lastSeenLocation
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RequestStatus;
    itemId: bigint;
    borrowTime: bigint;
    borrowerPrincipal: string;
}): {
    status: RequestStatus;
    itemId: bigint;
    borrowTime: bigint;
    borrowerPrincipal: string;
} {
    return {
        status: from_candid_RequestStatus_n23(_uploadFile, _downloadFile, value.status),
        itemId: value.itemId,
        borrowTime: value.borrowTime,
        borrowerPrincipal: value.borrowerPrincipal
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    hashtag: string;
    ownerPrincipal: string;
    name: string;
    description: string;
    pricePerDay: [] | [bigint];
    borrowerPrincipal: [] | [string];
    category: string;
    pricePerMonth: [] | [bigint];
    location: string;
}): {
    id: bigint;
    hashtag: string;
    ownerPrincipal: string;
    name: string;
    description: string;
    pricePerDay?: bigint;
    borrowerPrincipal?: string;
    category: string;
    pricePerMonth?: bigint;
    location: string;
} {
    return {
        id: value.id,
        hashtag: value.hashtag,
        ownerPrincipal: value.ownerPrincipal,
        name: value.name,
        description: value.description,
        pricePerDay: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.pricePerDay)),
        borrowerPrincipal: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.borrowerPrincipal)),
        category: value.category,
        pricePerMonth: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.pricePerMonth)),
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    active: null;
}): LostFoundStatus {
    return "resolved" in value ? LostFoundStatus.resolved : "active" in value ? LostFoundStatus.active : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    denied: null;
} | {
    approved: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "denied" in value ? RequestStatus.denied : "approved" in value ? RequestStatus.approved : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoundItem>): Array<FoundItem> {
    return value.map((x)=>from_candid_FoundItem_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LostItem>): Array<LostItem> {
    return value.map((x)=>from_candid_LostItem_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BorrowRequest>): Array<BorrowRequest> {
    return value.map((x)=>from_candid_BorrowRequest_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n5(_uploadFile, _downloadFile, x));
}
function to_candid_RequestStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): _RequestStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): {
    pending: null;
} | {
    denied: null;
} | {
    approved: null;
} {
    return value == RequestStatus.pending ? {
        pending: null
    } : value == RequestStatus.denied ? {
        denied: null
    } : value == RequestStatus.approved ? {
        approved: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
