/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BorrowRequest {
  'status' : RequestStatus,
  'itemId' : bigint,
  'borrowTime' : bigint,
  'borrowerPrincipal' : string,
}
export interface FoundItem {
  'id' : bigint,
  'status' : LostFoundStatus,
  'finderPrincipal' : string,
  'contactInfo' : string,
  'description' : string,
  'receiver' : [] | [string],
  'pickUpLocation' : string,
}
export interface Item {
  'id' : bigint,
  'hashtag' : string,
  'ownerPrincipal' : string,
  'name' : string,
  'description' : string,
  'pricePerDay' : [] | [bigint],
  'borrowerPrincipal' : [] | [string],
  'category' : string,
  'pricePerMonth' : [] | [bigint],
  'location' : string,
}
export type LostFoundStatus = { 'resolved' : null } |
  { 'active' : null };
export interface LostItem {
  'id' : bigint,
  'status' : LostFoundStatus,
  'contactInfo' : string,
  'description' : string,
  'reporterPrincipal' : string,
  'lastSeenLocation' : string,
}
export interface Profile { 'contactInfo' : string, 'name' : string }
export type RequestStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFoundItem' : ActorMethod<[string, string, string], bigint>,
  'addItem' : ActorMethod<
    [string, string, string, string, [] | [bigint], [] | [bigint], string],
    bigint
  >,
  'addLostItem' : ActorMethod<[string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBorrowRequest' : ActorMethod<[bigint, bigint], undefined>,
  'filterItemsByCategory' : ActorMethod<[string], Array<Item>>,
  'filterItemsByHashtag' : ActorMethod<[string], Array<Item>>,
  'getAllItems' : ActorMethod<[], Array<Item>>,
  'getAvailableItems' : ActorMethod<[], Array<Item>>,
  /**
   * / Get the caller's own profile. Requires #user role.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFoundItems' : ActorMethod<[], Array<FoundItem>>,
  /**
   * / Get items currently borrowed by a specific user.
   * / Caller must be that user or an admin to protect borrowing privacy.
   */
  'getItemsByBorrower' : ActorMethod<[string], Array<Item>>,
  'getItemsByOwner' : ActorMethod<[string], Array<Item>>,
  'getLostItems' : ActorMethod<[], Array<LostItem>>,
  /**
   * / Get borrow history for a given principal text. Caller must own that identity or be admin.
   */
  'getUserBorrowingHistory' : ActorMethod<[string], Array<BorrowRequest>>,
  /**
   * / Get any user's profile. Caller must be the same user or an admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resolveFoundItem' : ActorMethod<[bigint, string], undefined>,
  'resolveLostItem' : ActorMethod<[bigint], undefined>,
  /**
   * / Save the caller's own profile. Requires #user role.
   */
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'searchItemsByName' : ActorMethod<[string], Array<Item>>,
  'updateBorrowRequestStatus' : ActorMethod<[bigint, RequestStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];