/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Item = IDL.Record({
  'id' : IDL.Nat,
  'hashtag' : IDL.Text,
  'ownerPrincipal' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'pricePerDay' : IDL.Opt(IDL.Nat),
  'borrowerPrincipal' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'pricePerMonth' : IDL.Opt(IDL.Nat),
  'location' : IDL.Text,
});
export const Profile = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});
export const LostFoundStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'active' : IDL.Null,
});
export const FoundItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : LostFoundStatus,
  'finderPrincipal' : IDL.Text,
  'contactInfo' : IDL.Text,
  'description' : IDL.Text,
  'receiver' : IDL.Opt(IDL.Text),
  'pickUpLocation' : IDL.Text,
});
export const LostItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : LostFoundStatus,
  'contactInfo' : IDL.Text,
  'description' : IDL.Text,
  'reporterPrincipal' : IDL.Text,
  'lastSeenLocation' : IDL.Text,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'denied' : IDL.Null,
  'approved' : IDL.Null,
});
export const BorrowRequest = IDL.Record({
  'status' : RequestStatus,
  'itemId' : IDL.Nat,
  'borrowTime' : IDL.Nat,
  'borrowerPrincipal' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFoundItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addLostItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBorrowRequest' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'filterItemsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
  'filterItemsByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getAvailableItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFoundItems' : IDL.Func([], [IDL.Vec(FoundItem)], ['query']),
  'getItemsByBorrower' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
  'getItemsByOwner' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
  'getLostItems' : IDL.Func([], [IDL.Vec(LostItem)], ['query']),
  'getUserBorrowingHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BorrowRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resolveFoundItem' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'resolveLostItem' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'searchItemsByName' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
  'updateBorrowRequestStatus' : IDL.Func([IDL.Nat, RequestStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'hashtag' : IDL.Text,
    'ownerPrincipal' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'pricePerDay' : IDL.Opt(IDL.Nat),
    'borrowerPrincipal' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'pricePerMonth' : IDL.Opt(IDL.Nat),
    'location' : IDL.Text,
  });
  const Profile = IDL.Record({ 'contactInfo' : IDL.Text, 'name' : IDL.Text });
  const LostFoundStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'active' : IDL.Null,
  });
  const FoundItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : LostFoundStatus,
    'finderPrincipal' : IDL.Text,
    'contactInfo' : IDL.Text,
    'description' : IDL.Text,
    'receiver' : IDL.Opt(IDL.Text),
    'pickUpLocation' : IDL.Text,
  });
  const LostItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : LostFoundStatus,
    'contactInfo' : IDL.Text,
    'description' : IDL.Text,
    'reporterPrincipal' : IDL.Text,
    'lastSeenLocation' : IDL.Text,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  });
  const BorrowRequest = IDL.Record({
    'status' : RequestStatus,
    'itemId' : IDL.Nat,
    'borrowTime' : IDL.Nat,
    'borrowerPrincipal' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFoundItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addLostItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBorrowRequest' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'filterItemsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
    'filterItemsByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getAvailableItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFoundItems' : IDL.Func([], [IDL.Vec(FoundItem)], ['query']),
    'getItemsByBorrower' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
    'getItemsByOwner' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
    'getLostItems' : IDL.Func([], [IDL.Vec(LostItem)], ['query']),
    'getUserBorrowingHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BorrowRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resolveFoundItem' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'resolveLostItem' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'searchItemsByName' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
    'updateBorrowRequestStatus' : IDL.Func([IDL.Nat, RequestStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };